name: approval

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@1
        with:
          secret: ${{ github.TOKEN }}
          approvers: RPHAELLA
          minimum-approvals: 1
          issue-title: "Merge pull request #{{ github.event.pull_request.number }}"
          issue-body: "Please approve this pull request before merging it to main."
          exclude-workflow-initiator-as-approver: false